<a href="https://colab.research.google.com/github/chinwejoseph/Branch-Executive-Summary/blob/main/EXECUTIVE_SUMMARY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn import preprocessing

In [ ]:
#importing dataset unto google coolab to begin prepocessing
bank = pd.read_excel (r'Branch List.XLSX')
bank

,Unnamed: 0,Branch Name,Branch Location,State,City
0,1,DEIDE MINI,"DEIDE MARKET ROAD, OPPOSITE THE MARKET,DEIDE, ...",ABUJA,Deide
1,2,GWAGWALADA,"PLOT 415, Specialist hospital road gwagwalada",ABUJA,Gwagalada
2,3,KUBWA MINI,PLOT CM71/72 GADO NASKO ROAD,ABUJA,Kubwa
3,4,SULEJA,"Minna Road,Opposite Force A Division,Suleja",NIGER,SULEJA
4,5,BAUCHI,"16, YANDOKA ROAD",BAUCH,BAUCHI
...,...,...,...,...,...
125,126,KWARA MALL,KWARA STATE,KWARA,ILORIN
126,127,OGBOMOSHO,"Ogbomosho, Ilorin Road Ogbomosho Ogbomosho",OYO,OGBOMOSHO
127,128,OJATUNTUN,171 ABDULAZEEZ ATTAH ROAD,KWARA,OJATUNTUN
128,129,ONDO,"62, Yaba Road, Ondo Ondo",ONDO,ONDO
129,130,OSHOGBO,201 GBOGAN - IBADAN ROAD OSHOGBO,OSUN,OSHOGBO

In [ ]:
#to check the data type
bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       130 non-null    int64
 1   Branch Name      130 non-null    object
 2   Branch Location  130 non-null    object
 3   State            130 non-null    object
 4   City             130 non-null    object
dtypes: int64(1), object(4)
memory usage: 5.2+ KB

In [ ]:
#removing unneccessary column
bank2 = bank [['Branch Name', 'Branch Location', 'State', 'City']]
bank2

,Branch Name,Branch Location,State,City
0,DEIDE MINI,"DEIDE MARKET ROAD, OPPOSITE THE MARKET,DEIDE, ...",ABUJA,Deide
1,GWAGWALADA,"PLOT 415, Specialist hospital road gwagwalada",ABUJA,Gwagalada
2,KUBWA MINI,PLOT CM71/72 GADO NASKO ROAD,ABUJA,Kubwa
3,SULEJA,"Minna Road,Opposite Force A Division,Suleja",NIGER,SULEJA
4,BAUCHI,"16, YANDOKA ROAD",BAUCH,BAUCHI
...,...,...,...,...
125,KWARA MALL,KWARA STATE,KWARA,ILORIN
126,OGBOMOSHO,"Ogbomosho, Ilorin Road Ogbomosho Ogbomosho",OYO,OGBOMOSHO
127,OJATUNTUN,171 ABDULAZEEZ ATTAH ROAD,KWARA,OJATUNTUN
128,ONDO,"62, Yaba Road, Ondo Ondo",ONDO,ONDO
129,OSHOGBO,201 GBOGAN - IBADAN ROAD OSHOGBO,OSUN,OSHOGBO

In [ ]:
#correcting the spelling error within the 'city' column
bank2['City'] = bank2['City'].replace ('KADDUNA', 'KADUNA')
bank2

<ipython-input-10-5f0227a3166a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bank2['City'] = bank2['City'].replace ('KADDUNA', 'KADUNA')

,Branch Name,Branch Location,State,City
0,DEIDE MINI,"DEIDE MARKET ROAD, OPPOSITE THE MARKET,DEIDE, ...",ABUJA,Deide
1,GWAGWALADA,"PLOT 415, Specialist hospital road gwagwalada",ABUJA,Gwagalada
2,KUBWA MINI,PLOT CM71/72 GADO NASKO ROAD,ABUJA,Kubwa
3,SULEJA,"Minna Road,Opposite Force A Division,Suleja",NIGER,SULEJA
4,BAUCHI,"16, YANDOKA ROAD",BAUCH,BAUCHI
...,...,...,...,...
125,KWARA MALL,KWARA STATE,KWARA,ILORIN
126,OGBOMOSHO,"Ogbomosho, Ilorin Road Ogbomosho Ogbomosho",OYO,OGBOMOSHO
127,OJATUNTUN,171 ABDULAZEEZ ATTAH ROAD,KWARA,OJATUNTUN
128,ONDO,"62, Yaba Road, Ondo Ondo",ONDO,ONDO
129,OSHOGBO,201 GBOGAN - IBADAN ROAD OSHOGBO,OSUN,OSHOGBO

In [ ]:
#viewing the corrected variable
correct_values_bank2 = bank2[bank2['City'] == 'KADUNA']

In [ ]:
print(correct_values_bank2)

            Branch Name                              Branch Location   State  \
70          KADUNA MAIN                   14 Ahmadu Bello Way Kaduna  KADUNA
73  KADUNA CENTRAL MINI  1 BAYAJIDA ROAD,CENTRAL MARKET,KADUNA NORTH  KADUNA

      City
70  KADUNA
73  KADUNA